# Generated by Django 5.2.1 on 2025-05-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(max_length=16, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
            options={
                'verbose_name': '人员信息',
                'db_table': 'person',
                'managed': True,
            },
        ),
    ]
